apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: ivanushkaa/spring-web
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secrets
          readinessProbe:
            httpGet:
              path: /api/v1/students
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/students
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20